config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get 'requirements', :to => 'requirements#index'

match '/requirements/show/:id', :to => 'requirements#show', :via => :get, :constraints => { :id => /[\w+\.%-]+/ }

match '/requirements/auto_complete', :to => 'auto_completes#requirements', :via => :get, :as => 'auto_complete_requirements'
match '/requirement_links/add_link', :controller => :requirement_links, :action => 'add_link', :via => [:post]
match '/requirement_links/del_link', :controller => :requirement_links, :action => 'del_link', :via => [:post, :delete, :get]

match '/requirements/trace', :controller => :requirements, :action => 'trace', :via => [:get]
match 'projects/:id/requirements_settings/:action', :controller => 'requirements_settings', :via => [:get, :post, :put]

app/controllers/requirement_links_controller.rb
require 'uri'

class RequirementLinksController < ApplicationController
  unloadable

  before_filter :find_project, :only => [ :add_link, :del_link ]

  #def index
  #  @requirements = []
  #  return if Requirement.all.nil?
  #  Requirement.all.each do |r|
  #    @requirements << r if r.project_id == params[:project_id]
  #  end
  #
  #  linked_pages
  #end

  def add_link( context={} )
    rid = params[:requirement][:req_id]
    iid = params[:requirement][:issue_id]
    type = params[:requirement][:requirement_type]
    
    Rails.logger.info "!!!!!!!!!!!!! add iid=#{iid} rid=#{rid}"

    Requirement.link_issue(rid,iid,type)

    @issue = Issue.find( :first, :conditions => ['id = ?',iid] )
    #redirect_to issue_path(@issue)
    #return

    respond_to do |format|
      format.html { redirect_to issue_path(@issue) }
      format.js {  }
      format.api {
        render :action => 'show', :status => :created, :location => 'aaa'
      }
    end
  end

  def del_link( context={} )
    Rails.logger.info "!!!!!!!!!!!!! delete_link context='#{context.inspect}'"
    Rails.logger.info "!!!!!!!!!!!!! delete_link params='#{params.inspect}'"

    rid = params[:requirement][:req_id]
    iid = params[:requirement][:issue_id]
    Rails.logger.info "!!!!!!!!!!!!! delete iid=#{iid} rid=#{rid}"

    Requirement.unlink_issue(rid,iid)

    @issue = Issue.find( :first, :conditions => ['id = ?',iid] )

    respond_to do |format|
      format.html { redirect_to issue_path(@issue) }
      format.js
      format.api { render_api_ok }
    end
  end


  def self.collection_for_requirement_type_select
    values = RequirementIssueLink::TYPES
    values.keys.sort{|x,y| values[x][:order] <=> values[y][:order]}.collect{|k| [l(values[k][:name]), k]}
  end

  private

  def find_project
    @project = Project.find(params[:requirement][:project_id])
  end
end

app/views/requirement_links/_form.html.erb
<%= error_messages_for 'requirement' %>

<p><%= f.select :requirement_type, RequirementLinksController.collection_for_requirement_type_select, {}, :onchange => "setPredecessorFieldsVisibility();" %>
<%= l(:label_req_id) %> #<%= f.text_field :req_id, :size => 10 %>
<span id="predecessor_fields" style="display:none;">
<%= l(:field_delay) %>: <%= f.text_field :delay, :size => 3 %> <%= l(:label_day_plural) %>
<%= f.text_field :issue_id, :value => issue.id %>
<%= f.text_field :project_id, :value => project.id %>
</span>
<%= submit_tag l(:button_add) %>
<%= link_to_function l(:button_cancel), '$("#new-requirement-form").hide();'%>
</p>

<%= javascript_tag "observeAutocompleteField('requirement_req_id', '#{escape_javascript auto_complete_requirements_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>

<%= javascript_tag "setPredecessorFieldsVisibility();" %>

app/views/requirement_links/_issue_reqs.html.erb
<hr/>
<div id="requirements">
<%= render :partial => 'requirement_links/show' %>
</div>

app/views/requirement_links/_show.html.erb
<div class="contextual">
<% if User.current.allowed_to?(:manage_issue_relations, @project) %>
  <%= toggle_link l(:button_add), 'new-requirement-form', {:focus => 'requirement_issue_to_id'} %>
<% end %>
</div>
<p><strong>Требования</strong></p>
<% @reqs = Requirement.linked_reqs(@issue.id) %>
<% if @reqs.present? %>
<form>
<table class="list issues">
<% @reqs.each do |r| %>
  <% req = r[:req] -%>
  <tr class="issue hascontextmenu" id="requirement-<%= req.id %>">
  <td class="subject">
    <%= l(:label_req_traces_from) if r[:link_type] == 1 %>
    <%= l(:label_req_traces_to) if r[:link_type] == 2 %>
    <%= link_to "#{req.req_id} - #{req.text.truncate(100)}", RequirementsHelper.url_of_requirement(req,@project) %>
  </td>
  <td class="status"></td>
  <td class="start_date"></td>
  <td class="due_date"></td>
  <td class="buttons"><%= link_to image_tag('link_break.png'),
                                  { :controller => :requirement_links, :action => 'del_link', :requirement => { :issue_id => @issue.id, :req_id => req.id, :project_id => @project.id } },
                                  { :confirm => l(:text_are_you_sure), :method => :post, :remote => true } %></td>
  </tr>
<% end %>
</table>
</form>
<% end %>

<%= form_for @requirement, {
                 :as => :requirement, :remote => true,
                 :url => "/requirement_links/add_link",
                 :method => :post,
                 :rel => 'nofollow',
                 :html => {:id => 'new-requirement-form', :style => 'display: none;'}
               } do |f| %>
<%= render :partial => 'requirement_links/form', :locals => {:f => f, :issue => @issue, :project => @project }%>
<% end %>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'requirements', :plugin => 'redmine_requirements_plugin', :media => "screen" %>
<% end %>

app/views/requirement_links/add_link.js.erb
$('#requirements').html('<%= escape_javascript(render :partial => 'requirement_links/show') %>');
  $('#requirement_delay').val('');
  $('#requirement_req_id').val('');
  $('#requirement_req_id').focus();
$('#new-requirement-form').show();

app/views/requirement_links/del_link.js.erb
$('#requirement-<%= @req.id %>').remove();
$('#requirements').html('<%= escape_javascript(render :partial => 'requirement_links/show') %>');